# Gradle 配置
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m
org.gradle.daemon=true
# Minecraft 和 Forge 版本
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

# Mod 基本信息
mod_id=maid_weapon
mod_name=\u8f66\u4e07\u5973\u4ec6\uff1a\u5951\u7ea6\u4e4b\u5203
mod_license=MIT
mod_version=0.1.0-beta.1
mod_group_id=com.maidweapon
mod_authors=_Cazs_
mod_description=\u8f66\u4e07\u5973\u4ec6\u9644\u5c5eMod\u2014\u2014\u5c06\u5973\u4ec6\u4e0e\u6b66\u5668\u7f14\u7ed3\u5951\u7ea6\uff0c\u652f\u6301\u5951\u7ea6\u663e\u73b0\u3001\u5171\u9e23\u6210\u957f\u4e0e\u591a\u6a21\u7ec4\u6b66\u5668\u9002\u914d\u3002
