const fs=require('fs'),assert=require('assert/strict'),sharp=require('sharp'),dir=__dirname;
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),report=read(dir+'/structure.json'),old=read(report.source),next=read(dir+'/akatsuki-b-structure.bbmodel'),removed=new Set(report.removed),added=new Set(report.pieces.map(c=>c.uuid)),byId=new Map(next.elements.map(c=>[c.uuid,c]));
function bones(nodes,result=[]){for(const n of nodes)if(typeof n==='object'){const {children,...data}=n;result.push(data);bones(children||[],result);}return result;}
assert.deepEqual(bones(next.outliner),bones(old.outliner));assert.deepEqual(next.animations,old.animations);
assert.equal(next.elements.length,old.elements.length-removed.size+added.size);
assert.equal(removed.size,36);assert.equal(added.size,29);
for(const c of old.elements){if(removed.has(c.uuid)){assert.ok(!byId.has(c.uuid));continue;}const n=byId.get(c.uuid);assert.ok(n);for(const k of ['name','from','to','origin','rotation','inflate','visibility'])assert.deepEqual(n[k],c[k],c.uuid+':'+k);}
function parents(nodes,parent='',result=new Map()){for(const n of nodes){if(typeof n==='string')result.set(n,parent);else parents(n.children||[],n.uuid,result);}return result;}
const op=parents(old.outliner),np=parents(next.outliner);for(const [id,parent]of op)if(!removed.has(id))assert.equal(np.get(id),parent);
for(const p of report.pieces){assert.ok(byId.has(p.uuid));assert.ok(!old.elements.some(e=>e.uuid===p.uuid));}
async function main(){const a=await sharp(Buffer.from(old.textures[0].source.split(',')[1],'base64')).ensureAlpha().raw().toBuffer({resolveWithObject:true}),b=await sharp(dir+'/akatsuki-b-structure.png').ensureAlpha().raw().toBuffer({resolveWithObject:true}),embedded=await sharp(Buffer.from(next.textures[0].source.split(',')[1],'base64')).ensureAlpha().raw().toBuffer();assert.ok(b.data.equals(embedded));assert.equal(next.textures.length,1);assert.equal(b.info.width,512);
 function sample(image,uv,u,v){const {width,height}=image.info,x=Math.max(0,Math.min(width-1,Math.floor(uv[0]+(uv[2]-uv[0])*u))),y=Math.max(0,Math.min(height-1,Math.floor(uv[1]+(uv[3]-uv[1])*v))),i=(y*width+x)*4;return image.data.subarray(i,i+4);}
 let samples=0;for(const c of old.elements){if(removed.has(c.uuid))continue;const n=byId.get(c.uuid);for(const [side,f]of Object.entries(c.faces||{})){if(f.texture===null||!f.uv)continue;const nf=n.faces[side];assert.notEqual(nf.texture,null);for(let y=0;y<16;y++)for(let x=0;x<16;x++){const u=(x+.37)/16,v=(y+.41)/16;assert.ok(sample(a,f.uv,u,v).equals(sample(b,nf.uv,u,v)),c.uuid+':'+side+':'+x+','+y);samples++;}}}
 const geo=read(dir+'/akatsuki-b-structure.geo.json'),model=geo['minecraft:geometry'][0];assert.equal(model.description.texture_width,512);assert.equal(model.bones.flatMap(b=>b.cubes||[]).length,next.elements.length);for(const b of model.bones)for(const c of b.cubes||[])assert.ok([...c.origin,...c.size,...(c.rotation||[])].every(Number.isFinite));
 const diagonal=report.pieces.filter(p=>p.kind==='diagonal').sort((a,b)=>b.to[1]-a.to[1]);for(let i=1;i<diagonal.length;i++){assert.ok(diagonal[i].to[1]>diagonal[i-1].from[1]);assert.ok(diagonal[i].to[0]-diagonal[i].from[0]>diagonal[i-1].to[0]-diagonal[i-1].from[0]);}
 report.independentValidation={pass:true,removedSkirtCubes:36,newSkirtCubes:29,cubes:next.elements.length,bones:bones(next.outliner).length,unrelatedTextureSamples:samples,unrelatedGeometryAndParentsUnchanged:true,bonesAndAnimationsUnchanged:true,headMoonUnchanged:true,layeredSkirtGeometry:true,diagonalPanelsConnected:true,bedrockExportValid:true,texture:[512,512]};fs.writeFileSync(dir+'/structure.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report.independentValidation));}
main().catch(e=>{console.error(e);process.exitCode=1;});
