(() => {
const fs=require('fs'),dir='E:/Little maid/art/akatsuki/midnight-b-side-polish',source='E:/Little maid/art/akatsuki/midnight-b-reconstructed/akatsuki-b-reconstructed.bbmodel';fs.mkdirSync(dir,{recursive:true});const old=JSON.parse(fs.readFileSync(source,'utf8'));Codecs.project.load(old,{path:source,no_file:true});Modes.options.edit.select();
const replace=['月纹黑外襟','开襟内金边','斜切外襟金边','黑外襟翻角红衬','翻角金边','外襟卷回折面','卷回金脚','斜襟反折红衬','红衬错层裙边'];const removed=Cube.all.filter(c=>replace.some(n=>c.name.includes(n))).map(c=>c.uuid);for(const id of removed)Cube.all.find(c=>c.uuid===id).remove();
const tex=Texture.all[0],canvas=document.createElement('canvas');canvas.width=canvas.height=2048;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(tex.img,0,0);let ax=514,ay=2,row=0;const pieces=[],modified=[],clamp=n=>Math.max(0,Math.min(255,Math.round(n))),mix=(a,b,t)=>a.map((v,i)=>v+(b[i]-v)*Math.max(0,Math.min(1,t)));
function alloc(w,h){if(ax+w+2>2046){ax=514;ay+=row;row=0;}if(ay+h+2>2046)throw Error('Atlas full');const p=[ax,ay];ax+=w+2;row=Math.max(row,h+2);return p;}
const pixels=ctx.getImageData(0,0,512,512).data;for(const c of Cube.all.filter(c=>c.name.startsWith('B3_连续侧后袍_'))){const f=c.faces.south,uv=f.uv.slice(),w=Math.max(2,Math.ceil(Math.abs(uv[2]-uv[0]))),h=Math.max(2,Math.ceil(Math.abs(uv[3]-uv[1]))),at=alloc(w,h),im=ctx.createImageData(w,h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const sx=Math.max(0,Math.min(511,Math.floor(uv[0]+(uv[2]-uv[0])*(x+.5)/w))),sy=Math.max(0,Math.min(511,Math.floor(uv[1]+(uv[3]-uv[1])*(y+.5)/h))),grain=(x+y)%3;im.data.set([28+grain,25+grain,34+grain,pixels[(sy*512+sx)*4+3]],(y*w+x)*4);}ctx.putImageData(im,...at);f.uv=[at[0],at[1],at[0]+w,at[1]+h];modified.push(c.uuid);}
Canvas.updateAll();Project.model_3d.updateMatrixWorld(true);
function cube(name,from,to,rot,origin,parent,kind){const bone=Group.all.find(g=>g.name===parent);if(!bone)throw Error(parent);const local=new THREE.Vector3(...origin).applyMatrix4(bone.mesh.matrixWorld.clone().invert()).add(new THREE.Vector3(...bone.origin)).toArray(),q=new THREE.Quaternion().setFromEuler(new THREE.Euler(...rot.map(n=>n*Math.PI/180),'ZYX')),nq=bone.mesh.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(q),e=new THREE.Euler().setFromQuaternion(nq,'ZYX'),move=p=>p.map((v,i)=>v-origin[i]+local[i]),c=new Cube({name,from:move(from),to:move(to),rotation:[e.x,e.y,e.z].map(n=>n*180/Math.PI),origin:local,box_uv:false,autouv:0}).addTo(bone).init();pieces.push({uuid:c.uuid,name,from,to,rotation:rot,origin,parent,kind});return c;}
const reference=fs.readFileSync('E:/Little maid/art/akatsuki/midnight-b-reconstructed/rebuild.js','utf8'),start=reference.indexOf('const gold='),end=reference.indexOf('for(let i=0;i<10;i++)');if(start<0||end<start)throw Error('Painter helper changed');const helperCode=reference.slice(start,end).replace('if(err>.30)','if(err>.02)').replace("if(kind==='counter'&&!back&&!flat)","if(kind==='counter'&&back)rgb=[27,24,33];if(kind==='counter'&&!back&&!flat)");const helpers=eval('(function(){'+helperCode+'return {panel,edge,draw};})()'),{panel,edge,draw}=helpers;
const top=[[1.4,23.62,-2.98],[2.5,23.62,-2.78],[3.6,23.62,-2.52]],hem=[[3.45,12.25,-4.10],[5.62,11.02,-3.13],[7.55,9.68,-1.40]],roll=[[3.68,11.68,-3.84],[5.80,10.42,-2.78],[7.76,9.02,-.85]],returnEdge=[[3.56,11.36,-3.58],[5.64,10.12,-2.50],[7.56,8.73,-.51]];
for(let i=0;i<2;i++){panel('B4_顺侧月纹外襟_'+i,[top[i],top[i+1],hem[i+1],hem[i]],'FR','counter');panel('B4_收缓翻角红衬_'+i,[hem[i],hem[i+1],roll[i+1],roll[i]],'FR','lining');edge('B4_连续斜边_'+i,hem[i],hem[i+1],'FR','gold',.13);}
edge('B4_开襟内金边',[2.55,16.1,-3.64],hem[0],'FR','gold',.13);
edge('B4_外侧接袍包边',[top[2][0],top[2][1],top[2][2]-.13],[hem[2][0],hem[2][1],hem[2][2]-.13],'FR','chest',.35);
edge('B4_内侧衣片搭接',[top[0][0],top[0][1],top[0][2]-.13],[hem[0][0],hem[0][1],hem[0][2]-.13],'FR','chest',.24);
const wrapPoint=(u,v)=>{const x=(1.6-3.3*u)*(1-v)+(-2.55-6.0*u)*v,y=23.64*(1-v)+(8.5+1.8*u)*v,z=-3.02-1.36*v+.20*Math.cos(u*Math.PI*4)-.12*Math.sin(v*Math.PI);return[x,y,z];};
for(let i=0;i<3;i++){const a=wrapPoint(i/3,1),b=wrapPoint((i+1)/3,1),next=p=>[p[0]*.995,p[1]-.25,p[2]+.33];panel('B4_贴袍斜襟红衬_'+i,[a,b,next(b),next(a)],'FFM','lining');}
draw(false);Project.name='赤月 · B 侧袍收缓';Project.saved=false;globalThis.akatsukiSideState={dir,source,old,removed,pieces,modified,hem,roll,returnEdge};return JSON.stringify({removed:removed.length,added:pieces.length,cubes:Cube.all.length,bones:Group.all.length});
})()
