const fs=require('fs'),assert=require('assert/strict'),sharp=require('sharp'),dir=__dirname,read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const r=read(dir+'/changes.json'),a=read(r.source),b=read(dir+'/akatsuki-b-side-polish.bbmodel'),removed=new Set(r.removed),modified=new Set(r.modified),map=new Map(b.elements.map(c=>[c.uuid,c]));
function bones(nodes,out=[]){for(const n of nodes)if(typeof n==='object'){const {children,...v}=n;out.push(v);bones(children||[],out);}return out;}
function parents(nodes,parent='',out=new Map()){for(const n of nodes)if(typeof n==='string')out.set(n,parent);else parents(n.children||[],n.uuid,out);return out;}
assert.deepEqual(bones(a.outliner),bones(b.outliner));assert.deepEqual(a.animations,b.animations);assert.equal(b.elements.length,a.elements.length-r.removed.length+r.pieces.length);assert.equal(b.elements.length,412);assert.ok(r.restPoseChecks.maxOriginError<1e-7);assert.ok(r.restPoseChecks.maxRotationErrorRadians<1e-6);const ap=parents(a.outliner),bp=parents(b.outliner);for(const c of a.elements){if(removed.has(c.uuid)){assert.ok(!map.has(c.uuid));continue;}const n=map.get(c.uuid);assert.ok(n);assert.equal(ap.get(c.uuid),bp.get(c.uuid));for(const k of ['name','from','to','origin','rotation','inflate','visibility'])assert.deepEqual(c[k],n[k],c.uuid+':'+k);}
for(let i=0;i<r.hem.length;i++){const d=r.roll[i].map((v,k)=>v-r.hem[i][k]);assert.ok(Math.abs(d[0])<.31);assert.ok(Math.abs(d[1])<.76);assert.ok(Math.abs(d[2])<.71);}
async function main(){const x=await sharp(Buffer.from(a.textures[0].source.split(',')[1],'base64')).ensureAlpha().raw().toBuffer({resolveWithObject:true}),y=await sharp(dir+'/akatsuki-b-side-polish.png').ensureAlpha().raw().toBuffer({resolveWithObject:true}),embedded=await sharp(Buffer.from(b.textures[0].source.split(',')[1],'base64')).ensureAlpha().raw().toBuffer();assert.ok(y.data.equals(embedded));assert.equal(b.textures.length,1);assert.equal(y.info.width,512);const sample=(im,uv,u,v)=>{const xx=Math.max(0,Math.min(im.info.width-1,Math.floor(uv[0]+(uv[2]-uv[0])*u))),yy=Math.max(0,Math.min(im.info.height-1,Math.floor(uv[1]+(uv[3]-uv[1])*v))),i=(yy*im.info.width+xx)*4;return im.data.subarray(i,i+4);};let samples=0;for(const c of a.elements){if(removed.has(c.uuid))continue;const n=map.get(c.uuid);for(const [side,f]of Object.entries(c.faces||{})){if(f.texture===null||modified.has(c.uuid)&&side==='south')continue;for(let py=0;py<16;py++)for(let px=0;px<16;px++){const u=(px+.37)/16,v=(py+.41)/16;assert.ok(sample(x,f.uv,u,v).equals(sample(y,n.faces[side].uv,u,v)),c.name+':'+side);samples++;}}}
const geo=read(dir+'/akatsuki-b-side-polish.geo.json')['minecraft:geometry'][0];assert.equal(geo.description.texture_width,512);assert.equal(geo.bones.flatMap(b=>b.cubes||[]).length,b.elements.length);for(const bone of geo.bones)for(const c of bone.cubes||[])assert.ok([...c.origin,...c.size,...(c.rotation||[])].every(Number.isFinite)&&c.size.every(v=>v>0));r.validation={pass:true,cubes:b.elements.length,bones:bones(b.outliner).length,texture:[512,512],unrelatedTextureSamples:samples,allRetainedGeometryAndParentsUnchanged:true,tailHeadHandsSleevesAnimationsUnchanged:true,onlyExistingSouthLiningFacesRecolored:r.modified.length,hemReturnDeltaZMax:Math.max(...r.hem.map((p,i)=>Math.abs(r.roll[i][2]-p[2]))),bedrockExportValid:true,runtimeTested:false};fs.writeFileSync(dir+'/changes.json',JSON.stringify(r,null,2));console.log(JSON.stringify(r.validation));}
main().catch(e=>{console.error(e);process.exitCode=1;});
