(() => {
const fs=require('fs'),out='E:/Little maid/art/akatsuki/polish-v4',source='E:/Little maid/art/akatsuki/polish-v3/akatsuki-drunk-moon-v3.bbmodel';fs.mkdirSync(out,{recursive:true});Codecs.project.load(JSON.parse(fs.readFileSync(source,'utf8')),{path:source,no_file:true});Modes.options.edit.select();Project.name='赤月 · 衣襟与垂褶 v4';
const tex=Texture.all[0],canvas=document.createElement('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(tex.img,0,0);const old=ctx.getImageData(0,0,256,256).data,used=new Uint8Array(65536),targets=new Set(),changes=[];
const ancestry=c=>{const a=[];for(let p=c.parent;p&&p.name;p=p.parent)a.push(p.name);return a;};
for(const c of Cube.all)for(const f of Object.values(c.faces)){if(f.texture===null)continue;const uv=f.uv;for(let y=Math.max(0,Math.floor(Math.min(uv[1],uv[3]))-1);y<Math.min(256,Math.ceil(Math.max(uv[1],uv[3]))+1);y++)for(let x=Math.max(0,Math.floor(Math.min(uv[0],uv[2]))-1);x<Math.min(256,Math.ceil(Math.max(uv[0],uv[2]))+1);x++)used[y*256+x]=1;}
const protectedPixels=used.slice();
const owners=new Uint16Array(65536),allowed=new Uint8Array(65536);
for(const c of Cube.all)for(const f of Object.values(c.faces)){if(f.texture===null)continue;const uv=f.uv;for(let y=Math.floor(Math.min(uv[1],uv[3]));y<Math.ceil(Math.max(uv[1],uv[3]));y++)for(let x=Math.floor(Math.min(uv[0],uv[2]));x<Math.ceil(Math.max(uv[0],uv[2]));x++)if(x>=0&&x<256&&y>=0&&y<256)owners[y*256+x]++;}
function alloc(w,h){for(let y=1;y+h+1<256;y++)for(let x=1;x+w+1<256;x++){let free=true;for(let py=y-1;py<=y+h&&free;py++)for(let px=x-1;px<=x+w;px++)if(used[py*256+px]){free=false;break;}if(free){for(let py=y-1;py<=y+h;py++)for(let px=x-1;px<=x+w;px++)used[py*256+px]=1;return[x,y];}}throw Error('Atlas space exhausted '+w+'x'+h);}
const clamp=v=>Math.max(0,Math.min(255,Math.round(v)));
function paint(c,side,w,h,draw){const f=c.faces[side],uv=f.uv.slice();if(f.texture===null||uv[0]===uv[2]||uv[1]===uv[3])return;let dst,reused=false;const left=Math.min(uv[0],uv[2]),top=Math.min(uv[1],uv[3]),ow=Math.abs(uv[2]-uv[0]),oh=Math.abs(uv[3]-uv[1]);let exclusive=uv[2]>uv[0]&&uv[3]>uv[1];for(let y=top;y<top+oh&&exclusive;y++)for(let x=left;x<left+ow;x++)if(owners[y*256+x]!==1){exclusive=false;break;}if(exclusive&&ow>=4&&oh>=4){dst=[left,top];w=ow;h=oh;reused=true;for(let y=top-1;y<=top+oh;y++)for(let x=left-1;x<=left+ow;x++)if(x>=0&&x<256&&y>=0&&y<256)allowed[y*256+x]=1;}else dst=alloc(w,h);const patch=ctx.createImageData(w,h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const u=(x+.5)/w,v=(y+.5)/h,sx=Math.max(0,Math.min(255,Math.floor(uv[0]+(uv[2]-uv[0])*u))),sy=Math.max(0,Math.min(255,Math.floor(uv[1]+(uv[3]-uv[1])*v))),i=(sy*256+sx)*4;patch.data.set(draw(u,v,[old[i],old[i+1],old[i+2],old[i+3]]).map(clamp),(y*w+x)*4);}ctx.putImageData(patch,dst[0],dst[1]);ctx.drawImage(canvas,dst[0],dst[1],w,1,dst[0],dst[1]-1,w,1);ctx.drawImage(canvas,dst[0],dst[1]+h-1,w,1,dst[0],dst[1]+h,w,1);ctx.drawImage(canvas,dst[0],dst[1]-1,1,h+2,dst[0]-1,dst[1]-1,1,h+2);ctx.drawImage(canvas,dst[0]+w-1,dst[1]-1,1,h+2,dst[0]+w,dst[1]-1,1,h+2);f.uv=[dst[0],dst[1],dst[0]+w,dst[1]+h];c.box_uv=false;targets.add(c.uuid);changes.push({cube:c.uuid,side,w,h,reused});}
Canvas.updateAll();Project.model_3d.updateMatrixWorld(true);
function position(c,side,u,v){c.mesh.geometry.computeBoundingBox();const b=c.mesh.geometry.boundingBox,min=b.min,max=b.max;let p;if(side==='north'||side==='south')p=new THREE.Vector3(min.x+(max.x-min.x)*u,max.y-(max.y-min.y)*v,side==='north'?min.z:max.z);else if(side==='east'||side==='west')p=new THREE.Vector3(side==='east'?max.x:min.x,max.y-(max.y-min.y)*v,min.z+(max.z-min.z)*u);else p=new THREE.Vector3(min.x+(max.x-min.x)*u,side==='up'?max.y:min.y,min.z+(max.z-min.z)*v);return c.mesh.localToWorld(p);}
const inner=Cube.all.filter(c=>['FM','FM1','FM2'].includes(c.parent?.name)&&!ancestry(c).includes('FOX'));
let hemY=Infinity;for(const c of inner)for(const u of [0,1])for(const v of [0,1])hemY=Math.min(hemY,position(c,'north',u,v).y);
for(const c of inner)for(const side of Object.keys(c.faces)){const uv=c.faces[side].uv,w=Math.max(4,Math.ceil(Math.abs(uv[2]-uv[0])*2)),h=Math.max(4,Math.ceil(Math.abs(uv[3]-uv[1])*2));paint(c,side,w,h,(u,v,p)=>{if(!p[3])return p;const pos=position(c,side,u,v),y=pos.y,x=pos.x,spread=.40+Math.max(0,23-y)*.085;
const fold1=-Math.exp(-1*(((x+spread)/.18)**2))*10,fold2=-Math.exp(-1*(((x-spread*.85)/.21)**2))*7,fold3=Math.exp(-1*(((x-.18)/.55)**2))*5;
const edge=-Math.min(12,Math.abs(x)*3.2),gather=-Math.max(0,1-Math.abs(y-23)/2)*7;
const light=Math.round((fold1+fold2+fold3+edge+gather)/2)*2;
if(y<hemY+.19)return[39,25,30,p[3]];if(y<hemY+.43)return[167+light*.3,122+light*.3,54+light*.2,p[3]];if(y<hemY+.63)return[76,24,34,p[3]];
return[119+light,30+light*.45,44+light*.65,p[3]];});}
const collarIds=new Set(['d42a77d3-7391-bb1a-502f-f4bef908d907','21916b88-716c-7034-13c0-dab1edf3cba2','0bea8f4c-56fe-0440-ff78-d37e923d9e7f','dff3a6f7-446f-d7ee-33a4-3634d9868e5a','be57128d-455c-2d96-5db8-023b643a4a8c','fa134129-1ddc-df70-70e6-01c664bbe06b']);
for(const c of Cube.all.filter(c=>collarIds.has(c.uuid)))for(const side of ['north','south']){const uv=c.faces[side].uv,w=Math.max(10,Math.ceil(Math.abs(uv[2]-uv[0])*2)),h=Math.max(6,Math.ceil(Math.abs(uv[3]-uv[1])*2));paint(c,side,w,h,(u,v,p)=>{if(!p[3])return p;const ivory=p[0]>160&&p[1]>145&&p[2]>135;if(!ivory)return p;const narrow=c.to[0]-c.from[0]<1.5;if(narrow&&u<.12)return[44,33,35,p[3]];const edge=Math.min(u,1-u),shade=edge<.15?-12:edge<.3?-5:0,overlap=v>.83?-5:0;return[235+shade+overlap,225+shade+overlap,205+shade+overlap,p[3]];});}
for(const c of Cube.all.filter(c=>['FL2','FR2'].includes(c.parent?.name)))for(const side of ['north','south']){const uv=c.faces[side].uv;paint(c,side,Math.max(8,Math.ceil(Math.abs(uv[2]-uv[0])*2)),Math.max(12,Math.ceil(Math.abs(uv[3]-uv[1])*2)),(u,v,p)=>{if(!p[3])return p;const gold=p[0]>p[1]*1.13&&p[1]>p[2]*1.2&&p[1]>65;if(v>.95)return[31,24,29,p[3]];if(v>.89)return[157,114,49,p[3]];if(gold)return[30,24,29,p[3]];return p;});}
const pixels=ctx.getImageData(0,0,256,256).data;for(let i=0;i<65536;i++)if(protectedPixels[i]&&!allowed[i])for(let k=0;k<4;k++)if(pixels[i*4+k]!==old[i*4+k])throw Error('Unrelated texel changed');
const data=canvas.toDataURL('image/png');tex.fromDataURL(data);tex.name='akatsuki-clothing-v4.png';Canvas.updateAll();fs.writeFileSync(out+'/akatsuki-clothing-v4.png',Buffer.from(data.split(',')[1],'base64'));fs.writeFileSync(out+'/akatsuki-clothing-v4.bbmodel',Codecs.project.compile());
const report={source,targets:[...targets],changes,cubes:Cube.all.length,groups:Group.all.length,resolution:[256,256],hemY,unrelatedReferencedTexelsUnchanged:true,geometryChanged:false,bonesAndAnimationsChanged:false};fs.writeFileSync(out+'/validation.json',JSON.stringify(report,null,2));
for(const c of Cube.all)if(ancestry(c).includes('FOX'))c.visibility=false;Canvas.updateVisibility();const p=Preview.selected;p.controls.autoRotate=false;p.camera.position.set(0,25,-84);p.controls.target.set(0,21,0);p.camera.zoom=1;p.camera.updateProjectionMatrix();p.controls.update();Project.saved=false;
return JSON.stringify({targets:targets.size,faces:changes.length,hemY,resolution:report.resolution,cubes:report.cubes});
})()
