(() => {
const fs=require('fs'),dir='E:/Little maid/art/akatsuki/midnight-b-both-sides',source='E:/Little maid/art/akatsuki/midnight-b-side-polish/akatsuki-b-side-polish.bbmodel';fs.mkdirSync(dir,{recursive:true});const old=JSON.parse(fs.readFileSync(source,'utf8'));Codecs.project.load(old,{path:source,no_file:true});Modes.options.edit.select();
const removed=Cube.all.filter(c=>c.name.startsWith('B3_宽斜襟折面_')||c.name.startsWith('B3_斜襟错层金裙边_')||c.name.startsWith('B4_贴袍斜襟红衬_')).map(c=>c.uuid);for(const id of removed)Cube.all.find(c=>c.uuid===id).remove();
const tex=Texture.all[0],canvas=document.createElement('canvas');canvas.width=canvas.height=2048;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(tex.img,0,0);let ax=514,ay=2,row=0;const pieces=[],clamp=n=>Math.max(0,Math.min(255,Math.round(n))),mix=(a,b,t)=>a.map((v,i)=>v+(b[i]-v)*Math.max(0,Math.min(1,t)));
function alloc(w,h){if(ax+w+2>2046){ax=514;ay+=row;row=0;}if(ay+h+2>2046)throw Error('Atlas full');const p=[ax,ay];ax+=w+2;row=Math.max(row,h+2);return p;}
Canvas.updateAll();Project.model_3d.updateMatrixWorld(true);
function cube(name,from,to,rot,origin,parent,kind){const bone=Group.all.find(g=>g.name===parent);if(!bone)throw Error(parent);const local=new THREE.Vector3(...origin).applyMatrix4(bone.mesh.matrixWorld.clone().invert()).add(new THREE.Vector3(...bone.origin)).toArray(),q=new THREE.Quaternion().setFromEuler(new THREE.Euler(...rot.map(n=>n*Math.PI/180),'ZYX')),nq=bone.mesh.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(q),e=new THREE.Euler().setFromQuaternion(nq,'ZYX'),move=p=>p.map((v,i)=>v-origin[i]+local[i]),c=new Cube({name,from:move(from),to:move(to),rotation:[e.x,e.y,e.z].map(n=>n*180/Math.PI),origin:local,box_uv:false,autouv:0}).addTo(bone).init();pieces.push({uuid:c.uuid,name,from,to,rotation:rot,origin,parent,kind});return c;}
const reference=fs.readFileSync('E:/Little maid/art/akatsuki/midnight-b-reconstructed/rebuild.js','utf8'),start=reference.indexOf('const gold='),end=reference.indexOf('for(let i=0;i<10;i++)');if(start<0||end<start)throw Error('Painter helper changed');const helperCode=reference.slice(start,end).replace("density=kind==='crescent'?8:4","density=kind==='crescent'?8:6");const {panel,edge,draw}=eval('(function(){'+helperCode+'return {panel,edge,draw};})()');
const point=(u,v)=>{const x=(1.6-3.3*u)*(1-v)+(-2.55-4.10*u)*v,y=23.64*(1-v)+(8.5+.35*u)*v,z=-3.02-1.36*v+.20*Math.cos(u*Math.PI*4)-.08*Math.sin(v*Math.PI)-.42*Math.sin(v*Math.PI)*Math.sin(u*Math.PI)+2.56*u*u*v+.18*u*(1-v);return[x,y,z];};
for(let j=0;j<2;j++)for(let i=0;i<3;i++){const u0=i/3,u1=(i+1)/3,v0=j*.5,v1=(j+1)*.5;panel('B5_顺侧酒红斜襟_'+i+'_'+j,[point(u0,v0),point(u1,v0),point(u1,v1),point(u0,v1)],'FFM','wrap');}
const hem=[];for(let i=0;i<4;i++)hem.push(point(i/3,1));
for(let i=0;i<3;i++){const a=hem[i],b=hem[i+1],lining=p=>[p[0]*.995,p[1]-.22,p[2]+.24];edge('B5_随形斜襟金边_'+i,a,b,'FFM','gold',.14);panel('B5_随形窄红衬_'+i,[a,b,lining(b),lining(a)],'FFM','lining');}
draw(false);Project.name='赤月 · B 双侧衣襟衔接';Project.saved=false;globalThis.akatsukiBothSideState={dir,source,old,removed,pieces,hem};return JSON.stringify({removed:removed.length,added:pieces.length,cubes:Cube.all.length,bones:Group.all.length,hem});
})()
