const fs=require('fs'),assert=require('assert/strict'),sharp=require('sharp'),dir=__dirname;
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),report=read(dir+'/changes.json'),old=read(report.source),next=read(dir+'/akatsuki-midnight-b-final.bbmodel'),removed=new Set(report.removed),modified=new Set(report.modified),added=new Set(report.pieces.map(c=>c.uuid)),byId=new Map(next.elements.map(c=>[c.uuid,c]));
function bones(nodes,result=[]){for(const n of nodes)if(typeof n==='object'){const {children,...data}=n;result.push(data);bones(children||[],result);}return result;}
function parents(nodes,parent='',result=new Map()){for(const n of nodes){if(typeof n==='string')result.set(n,parent);else parents(n.children||[],n.uuid,result);}return result;}
assert.deepEqual(bones(next.outliner),bones(old.outliner));assert.deepEqual(next.animations,old.animations);assert.equal(next.elements.length,old.elements.length-removed.size+added.size);assert.equal(next.elements.length,395);
const op=parents(old.outliner),np=parents(next.outliner);
for(const c of old.elements){if(removed.has(c.uuid)){assert.ok(!byId.has(c.uuid));continue;}const n=byId.get(c.uuid);assert.ok(n);assert.equal(np.get(c.uuid),op.get(c.uuid));if(!report.modifiedGeometry.includes(c.uuid))for(const k of ['name','from','to','origin','rotation','inflate','visibility'])assert.deepEqual(n[k],c[k],c.uuid+':'+k);}
for(const p of report.pieces){assert.ok(byId.has(p.uuid));assert.ok(!old.elements.some(e=>e.uuid===p.uuid));}
assert.ok(report.restPoseChecks.maxOriginError<1e-7);assert.ok(report.restPoseChecks.maxRotationErrorRadians<1e-6);
const clasp=byId.get(report.modifiedGeometry[0]),waist=byId.get(report.pieces.find(p=>p.kind==='waist').uuid);for(const axis of [0,1])assert.ok(clasp.from[axis]>=waist.from[axis]&&clasp.to[axis]<=waist.to[axis]);assert.ok(clasp.from[2]<waist.from[2]&&clasp.to[2]>waist.from[2]);for(const side of ['east','west','up','down'])assert.equal(clasp.faces[side].texture,null);
async function main(){const a=await sharp(Buffer.from(old.textures[0].source.split(',')[1],'base64')).ensureAlpha().raw().toBuffer({resolveWithObject:true}),b=await sharp(dir+'/akatsuki-midnight-b-final.png').ensureAlpha().raw().toBuffer({resolveWithObject:true}),embedded=await sharp(Buffer.from(next.textures[0].source.split(',')[1],'base64')).ensureAlpha().raw().toBuffer();assert.ok(b.data.equals(embedded));assert.equal(next.textures.length,1);assert.equal(b.info.width,512);
 function sample(image,uv,u,v){const {width,height}=image.info,x=Math.max(0,Math.min(width-1,Math.floor(uv[0]+(uv[2]-uv[0])*u))),y=Math.max(0,Math.min(height-1,Math.floor(uv[1]+(uv[3]-uv[1])*v))),i=(y*width+x)*4;return image.data.subarray(i,i+4);}
 let samples=0;for(const c of old.elements){if(removed.has(c.uuid)||modified.has(c.uuid))continue;const n=byId.get(c.uuid);for(const [side,f]of Object.entries(c.faces||{})){if(f.texture===null||!f.uv)continue;const nf=n.faces[side];assert.notEqual(nf.texture,null);for(let y=0;y<16;y++)for(let x=0;x<16;x++){const u=(x+.37)/16,v=(y+.41)/16;assert.ok(sample(a,f.uv,u,v).equals(sample(b,nf.uv,u,v)),c.uuid+':'+side+':'+x+','+y);samples++;}}}
 const geo=read(dir+'/akatsuki-midnight-b-final.geo.json')['minecraft:geometry'][0];assert.equal(geo.description.texture_width,512);assert.equal(geo.bones.flatMap(b=>b.cubes||[]).length,next.elements.length);for(const bone of geo.bones)for(const c of bone.cubes||[]){assert.ok([...c.origin,...c.size,...(c.rotation||[])].every(Number.isFinite));assert.ok(c.size.every(n=>n>0));}
 const ribbons=new Map();for(const p of report.pieces)if(p.options.length){const family=p.name.replace(/_\d+$/,'');if(!ribbons.has(family))ribbons.set(family,[]);ribbons.get(family).push(p);}
 const down=(length,r)=>{const [x,y,z]=r.map(n=>n*Math.PI/180),a=[0,-length*Math.cos(x),-length*Math.sin(x)],v=[a[0]*Math.cos(y)+a[2]*Math.sin(y),a[1],-a[0]*Math.sin(y)+a[2]*Math.cos(y)];return[v[0]*Math.cos(z)-v[1]*Math.sin(z),v[0]*Math.sin(z)+v[1]*Math.cos(z),v[2]];};
 let joined=0;for(const [name,parts]of ribbons){if(!name.includes('宽斜襟')&&!name.includes('月纹开襟')&&!name.includes('细红结绳'))continue;parts.sort((a,b)=>a.options.start-b.options.start);for(let i=1;i<parts.length;i++){const a=parts[i-1],n=parts[i],delta=down(a.options.length*(a.options.end-a.options.start),a.rotation),wanted=a.origin.map((v,k)=>v+delta[k]);assert.ok(Math.hypot(...wanted.map((v,k)=>v-n.origin[k]))<1e-7,name);joined++;}}
 report.independentValidation={pass:true,cubes:next.elements.length,bones:bones(next.outliner).length,unrelatedTextureSamples:samples,unrelatedGeometryAndParentsUnchanged:true,bonesAndAnimationsUnchanged:true,headHandsFoxTailAndMoonUnchanged:true,joinedPanelHinges:joined,boneRotationCompensated:true,bedrockExportValid:true,texture:[b.info.width,b.info.height]};fs.writeFileSync(dir+'/changes.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report.independentValidation));}
main().catch(e=>{console.error(e);process.exitCode=1;});
