(() => {
const fs=require('fs'),out='E:/Little maid/art/akatsuki/midnight-b',source='E:/Little maid/art/akatsuki/polish-v5/akatsuki-back-moon-v5.bbmodel';fs.mkdirSync(out,{recursive:true});Codecs.project.load(JSON.parse(fs.readFileSync(source,'utf8')),{path:source,no_file:true});Modes.options.edit.select();
const names=c=>{const a=[];for(let p=c.parent;p&&p.name;p=p.parent)a.push(p.name);return a;};
const hands=new Set(['471fd222-f3c9-6f2f-d2cd-7a2c8fa7e99d','78183cc0-5413-05a7-9644-5cabed039756']);
const targets=Cube.all.filter(c=>!hands.has(c.uuid)&&!names(c).includes('FOX')&&(['UpperBody','LeftArm','RightArm','LeftForeArm','RightForeArm'].includes(c.parent?.name)||names(c).includes('clothe')));
const tex=Texture.all[0],canvas=document.createElement('canvas');canvas.width=canvas.height=1024;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(tex.img,0,0);const old=ctx.getImageData(0,0,256,256).data;
let cursorX=258,cursorY=2,rowHeight=0;const changes=[];
function alloc(w,h){if(cursorX+w+1>1022){cursorX=258;cursorY+=rowHeight;rowHeight=0;}if(cursorY+h+1>1022)throw Error('Atlas full');const p=[cursorX,cursorY];cursorX+=w+2;rowHeight=Math.max(rowHeight,h+2);return p;}
function point(c,side,u,v){c.mesh.geometry.computeBoundingBox();const b=c.mesh.geometry.boundingBox,min=b.min,max=b.max;let p;if(['north','south'].includes(side))p=new THREE.Vector3(side==='north'?max.x-(max.x-min.x)*u:min.x+(max.x-min.x)*u,max.y-(max.y-min.y)*v,side==='north'?min.z:max.z);else if(['east','west'].includes(side))p=new THREE.Vector3(side==='east'?max.x:min.x,max.y-(max.y-min.y)*v,side==='east'?max.z-(max.z-min.z)*u:min.z+(max.z-min.z)*u);else p=new THREE.Vector3(min.x+(max.x-min.x)*u,side==='up'?max.y:min.y,side==='down'?max.z-(max.z-min.z)*v:min.z+(max.z-min.z)*v);return c.mesh.localToWorld(p);}
Canvas.updateAll();Project.model_3d.updateMatrixWorld(true);
const clamp=n=>Math.max(0,Math.min(255,Math.round(n)));
function patch(c,side,w,h,draw){const f=c.faces[side],uv=f.uv.slice();if(f.texture===null)return;const dst=alloc(w,h),img=ctx.createImageData(w,h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const u=(x+.5)/w,v=(y+.5)/h,sx=Math.max(0,Math.min(255,Math.floor(uv[0]+(uv[2]-uv[0])*u))),sy=Math.max(0,Math.min(255,Math.floor(uv[1]+(uv[3]-uv[1])*v))),i=(sy*256+sx)*4,p=[old[i],old[i+1],old[i+2],old[i+3]],rgb=draw(u,v,p,point(c,side,u,v));img.data.set(rgb.map(clamp),(y*w+x)*4);}ctx.putImageData(img,dst[0],dst[1]);ctx.drawImage(canvas,dst[0],dst[1],w,1,dst[0],dst[1]-1,w,1);ctx.drawImage(canvas,dst[0],dst[1]+h-1,w,1,dst[0],dst[1]+h,w,1);ctx.drawImage(canvas,dst[0],dst[1]-1,1,h+2,dst[0]-1,dst[1]-1,1,h+2);ctx.drawImage(canvas,dst[0]+w-1,dst[1]-1,1,h+2,dst[0]+w,dst[1]-1,1,h+2);f.uv=[dst[0],dst[1],dst[0]+w,dst[1]+h];c.box_uv=false;changes.push({id:c.uuid,side});}
for(const c of targets){const skirt=names(c).includes('clothe'),fore=c.parent?.name.includes('ForeArm'),arm=c.parent?.name.includes('Arm'),upper=c.parent?.name==='UpperBody',inner=skirt&&names(c).some(n=>/^FF?M/.test(n));
for(const side of Object.keys(c.faces)){const width=['east','west'].includes(side)?c.to[2]-c.from[2]:c.to[0]-c.from[0],height=['up','down'].includes(side)?c.to[2]-c.from[2]:c.to[1]-c.from[1];patch(c,side,Math.max(4,Math.ceil(width*3)),Math.max(4,Math.ceil(height*3)),(u,v,p,pos)=>{
if(!p[3])return p;const x=pos.x,y=pos.y,fold=Math.round((Math.cos(x*2)*2+Math.cos(x*.85)*2)/2)*2;
const gold=p[0]>p[1]*1.13&&p[1]>p[2]*1.2&&p[1]>65,ivory=p[0]>160&&p[1]>145&&p[2]>135&&Math.max(...p.slice(0,3))-Math.min(...p.slice(0,3))<55;
if(arm){if(gold)return[164,120,49,p[3]];if(ivory&&y<20)return[234+fold,226+fold,207+fold,p[3]];const t=Math.max(0,Math.min(1,(y-21)/4));const base=[110+(1-t)*5,26,41];const ink=[32,28,33];let rgb=base.map((n,k)=>n+(ink[k]-n)*t+fold*.5);if(fore&&y>18.3&&y<20&&Math.abs((y-18.3)-(.62+Math.sin(x*4)*.09))<.09)rgb=[157,108,49];return[...rgb,p[3]];}
if(upper){if(y<25.7&&y>22.2)return[30+fold,25+fold,29+fold,p[3]];const line=(y-28.3)*.78;const d=x-line;const cream=(Math.abs(d)<.35&&y>26)||(Math.abs(x)<.65&&y>29.8);if(cream)return[230+fold,221+fold,205+fold,p[3]];const wine=d<-.35;return wine?[109+fold,27+fold*.5,43+fold*.6,p[3]]:[31+fold,27+fold,31+fold,p[3]];}
if(skirt){const center=(y-16)*.5+.35,dist=x-center,wrap=pos.z<1.0&&Math.abs(dist)<1.6;const lower=Math.max(0,Math.min(1,(15-y)/7));let rgb=[29+fold,26+fold,31+fold];if(wrap)rgb=[119+fold-lower*36,29+fold*.4-lower*10,43+fold*.65-lower*6];
if(wrap&&Math.abs(dist)>1.46)rgb=[130,88,42];
const moonX=2.75,moonY=15,r=Math.hypot((x-moonX)/1.25,(y-moonY)/1.65),cut=Math.hypot((x-moonX-.38)/1.04,(y-moonY-.06)/1.50);if(!wrap&&pos.z<0&&r<1&&cut>1&&y>12)rgb=[166+fold,121+fold,51];
if(!wrap&&pos.z<0&&x>1.7&&x<4.3&&Math.abs(y-(12.3+Math.sin(x*2.3)*.16))<.10)rgb=[106,48,51];
if(y<8.7)rgb=[146+fold,105+fold,46];if(y<8.36)rgb=[39,27,32];return[...rgb,p[3]];}
return p;});}}
const waist=Cube.all.find(c=>c.name==='AkatsukiWaistCrystal');
for(const side of ['north','south'])patch(waist,side,24,24,(u,v,p)=>{const outer=Math.hypot((u-.47)/.41,(v-.5)/.42),cut=Math.hypot((u-.63)/.35,(v-.47)/.36);if(outer<1&&cut>1)return[outer>.87?210:168,outer>.87?166:121,outer>.87?83:49,255];return[30,25,29,255];});
const bow=Cube.all.filter(c=>/^bow[LR][1-4]$/.test(c.parent?.name));for(const c of bow)for(const side of ['north','south'])patch(c,side,Math.max(6,Math.ceil((c.to[0]-c.from[0])*3)),Math.max(8,Math.ceil((c.to[1]-c.from[1])*3)),(u,v,p)=>u>.38&&u<.61?[120,30,42,p[3]]:v>.92?[155,110,47,p[3]]:[31,26,30,p[3]]);
tex.width=tex.height=tex.uv_width=tex.uv_height=1024;Project.texture_width=Project.texture_height=1024;tex.fromDataURL(canvas.toDataURL());Project.name='赤月 · 墨夜酒狐 B';Canvas.updateAll();
const report={source,targets:[...new Set(changes.map(c=>c.id))],changes,cubes:Cube.all.length,groups:Group.all.length,moonUnchanged:true,geometryChanged:false,design:'charcoal robe, diagonal wine wrap, dark-red sleeves, ivory turned cuffs, crescent obi, asymmetric moon embroidery'};fs.writeFileSync(out+'/validation.json',JSON.stringify(report,null,2));return JSON.stringify({targets:report.targets.length,faces:changes.length,moonUnchanged:true,stage:'ready for lossless packing'});
})()
