(() => {
const fs=require('fs'),out='E:/Little maid/art/akatsuki/midnight-b',tex=Texture.all[0],size=tex.width,canvas=document.createElement('canvas');canvas.width=canvas.height=size;const ctx=canvas.getContext('2d');ctx.drawImage(tex.img,0,0);const occupied=new Uint8Array(size*size);
for(const c of Cube.all)for(const f of Object.values(c.faces)){if(f.texture===null)continue;const uv=f.uv;for(let y=Math.floor(Math.min(uv[1],uv[3]));y<Math.ceil(Math.max(uv[1],uv[3]));y++)for(let x=Math.floor(Math.min(uv[0],uv[2]));x<Math.ceil(Math.max(uv[0],uv[2]));x++)if(x>=0&&x<size&&y>=0&&y<size)occupied[y*size+x]=1;}
const free=occupied.findIndex(v=>!v);if(free<0)throw Error('No constant swatch space');const bx=free%size,by=Math.floor(free/size);ctx.fillStyle='#1e191d';ctx.fillRect(bx,by,1,1);
const hiddenKnot=Cube.all.filter(c=>c.parent?.name==='bow');for(const c of hiddenKnot)for(const f of Object.values(c.faces)){f.texture=tex.uuid;f.uv=[bx,by,bx+1,by+1];}
const clasp=Cube.all.find(c=>c.name==='AkatsukiWaistCrystal');clasp.from=[-1,23.39844,-3.9];clasp.to=[1,25.39844,-3.7];clasp.rotation=[0,0,0];clasp.visibility=true;
const uv=clasp.faces.north.uv,w=uv[2]-uv[0],h=uv[3]-uv[1],patch=ctx.createImageData(w,h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const u=(x+.5)/w,v=(y+.5)/h,r=Math.hypot((u-.47)/.41,(v-.5)/.42),cut=Math.hypot((u-.64)/.35,(v-.47)/.36);patch.data.set(r<1&&cut>1?[r>.87?224:179,r>.87?178:128,r>.87?87:53,255]:[0,0,0,0],(y*w+x)*4);}ctx.putImageData(patch,uv[0],uv[1]);for(const f of Object.values(clasp.faces)){f.texture=tex.uuid;f.uv=uv.slice();}
tex.fromDataURL(canvas.toDataURL());for(const c of [...hiddenKnot,clasp]){c.preview_controller.updateGeometry(c);c.preview_controller.updateFaces(c);c.preview_controller.updateUV(c);}Canvas.updateAll();
const original=JSON.parse(fs.readFileSync('E:/Little maid/art/akatsuki/polish-v5/akatsuki-back-moon-v5.bbmodel','utf8')),byId=new Map(original.elements.map(e=>[e.uuid,e]));for(const c of Cube.all)c.visibility=byId.get(c.uuid).visibility!==false;Canvas.updateVisibility();
fs.writeFileSync(out+'/akatsuki-midnight-b.bbmodel',Codecs.project.compile());fs.writeFileSync(out+'/akatsuki-midnight-b.png',Buffer.from(canvas.toDataURL().split(',')[1],'base64'));const report=JSON.parse(fs.readFileSync(out+'/validation.json','utf8'));report.targets=[...new Set([...report.targets,...hiddenKnot.map(c=>c.uuid)])];report.changedGeometry=[clasp.uuid];report.geometryChanged=true;report.claspSupport={support:'original bow centre',rearZ:-3.7,supportFrontZ:-3.775,embedded:.075};report.resolution=[size,size];report.moonUnchanged=true;fs.writeFileSync(out+'/validation.json',JSON.stringify(report,null,2));
for(const c of Cube.all){let p=c.parent;while(p&&p.name){if(p.name==='FOX'){c.visibility=false;break;}p=p.parent;}}Canvas.updateVisibility();return JSON.stringify({resolution:report.resolution,claspExposed:true,geometryChanged:report.changedGeometry,cubes:Cube.all.length});
})()
