(() => {
Canvas.updateAll();Project.model_3d.updateMatrixWorld(true);const s=globalThis.akatsukiOptimizeState,tex=Texture.all[0],canvas=document.createElement('canvas');canvas.width=tex.width;canvas.height=tex.height;const ctx=canvas.getContext('2d');ctx.drawImage(tex.img,0,0);const raw=ctx.getImageData(0,0,tex.width,tex.height).data;
function alpha(f){if(f.texture===null)return 'disabled';let opaque=true,empty=true;const u=f.uv;for(let y=Math.floor(Math.min(u[1],u[3]));y<Math.ceil(Math.max(u[1],u[3]));y++)for(let x=Math.floor(Math.min(u[0],u[2]));x<Math.ceil(Math.max(u[0],u[2]));x++){const a=raw[(Math.max(0,Math.min(tex.height-1,y))*tex.width+Math.max(0,Math.min(tex.width-1,x)))*4+3];if(a!==255)opaque=false;if(a!==0)empty=false;}return opaque?'opaque':empty?'empty':'masked';}
const all=Cube.all.slice(),beforeFaces=all.reduce((n,c)=>n+Object.values(c.faces).filter(f=>f.texture!==null).length,0),supports=all.filter(c=>c.export!==false&&c.visibility!==false&&Object.values(c.faces).every(f=>alpha(f)==='opaque')),cuts=[];
function corners(c,side){const i=c.inflate||0,lo=c.from.map(v=>v-i),hi=c.to.map(v=>v+i),out=[];for(const a of [0,1])for(const b of [0,1]){let v;if(side==='north'||side==='south')v=[a?hi[0]:lo[0],b?hi[1]:lo[1],side==='north'?lo[2]:hi[2]];else if(side==='east'||side==='west')v=[side==='west'?lo[0]:hi[0],a?hi[1]:lo[1],b?hi[2]:lo[2]];else v=[a?hi[0]:lo[0],side==='down'?lo[1]:hi[1],b?hi[2]:lo[2]];out.push(c.mesh.localToWorld(new THREE.Vector3(...v).sub(new THREE.Vector3(...c.origin))));}return out;}
for(const c of all)for(const [side,f]of Object.entries(c.faces)){if(f.texture===null)continue;if(alpha(f)==='empty'){cuts.push({uuid:c.uuid,name:c.name,side,reason:'fully-transparent-UV'});continue;}const points=corners(c,side),center=points.reduce((v,p)=>v.add(p),new THREE.Vector3()).multiplyScalar(.25),normal=new THREE.Vector3(...({north:[0,0,-1],south:[0,0,1],west:[-1,0,0],east:[1,0,0],up:[0,1,0],down:[0,-1,0]})[side]).applyQuaternion(c.mesh.getWorldQuaternion(new THREE.Quaternion())),outward=center.clone().addScaledVector(normal,.01);let reason='';const target=supports.find(t=>{if(t===c||t.parent!==c.parent)return false;const local=v=>t.mesh.worldToLocal(v.clone()).add(new THREE.Vector3(...t.origin)),i=t.inflate||0,inside=(p,margin)=>[0,1,2].every(k=>p.getComponent(k)>t.from[k]-i+margin&&p.getComponent(k)<t.to[k]+i-margin);if(points.every(v=>inside(local(v),.025))){reason='strictly-inside-opaque-same-bone';return true;}if(points.every(v=>inside(local(v),-1e-7))&&inside(local(outward),.001)){reason='covered-contact-face-same-bone';return true;}return false;});if(target)cuts.push({uuid:c.uuid,name:c.name,side,reason,support:target.uuid});}
for(const cut of cuts)Cube.all.find(c=>c.uuid===cut.uuid).faces[cut.side].texture=null;
const emptyCubes=Cube.all.filter(c=>Object.values(c.faces).every(f=>f.texture===null)).map(c=>({uuid:c.uuid,name:c.name,parent:c.parent.uuid}));for(const item of emptyCubes)Cube.all.find(c=>c.uuid===item.uuid).remove();
const afterFaces=Cube.all.reduce((n,c)=>n+Object.values(c.faces).filter(f=>f.texture!==null).length,0);s.cuts=cuts;s.removed=emptyCubes;s.stats={beforeCubes:all.length,afterCubes:Cube.all.length,beforeFaces,afterFaces,removedFaces:beforeFaces-afterFaces,removedTriangles:(beforeFaces-afterFaces)*2,opaqueSupports:supports.length,bones:Group.all.length};Project.saved=false;Canvas.updateAll();require('fs').writeFileSync(s.dir+'/culling-report.json',JSON.stringify({source:s.source,stats:s.stats,cuts,removed:emptyCubes},null,2));return {stats:s.stats,byReason:cuts.reduce((m,c)=>(m[c.reason]=(m[c.reason]||0)+1,m),{}),removed:emptyCubes};
})()
