const fs=require('fs'),assert=require('assert/strict'),sharp=require('sharp'),dir=__dirname,read=p=>JSON.parse(fs.readFileSync(p,'utf8')),r=read(dir+'/culling-report.json'),a=read(r.source),b=read(dir+'/akatsuki-b-optimized.bbmodel'),am=new Map(a.elements.map(c=>[c.uuid,c])),bm=new Map(b.elements.map(c=>[c.uuid,c])),cutMap=new Map(r.cuts.map(c=>[c.uuid+':'+c.side,c]));
function parents(nodes,parent='',out=new Map()){for(const n of nodes)if(typeof n==='string')out.set(n,parent);else parents(n.children||[],n.uuid,out);return out;}
const ap=parents(a.outliner),bp=parents(b.outliner);assert.deepEqual(a.outliner,b.outliner);assert.deepEqual(a.animations,b.animations);assert.deepEqual(a.resolution,b.resolution);assert.equal(a.elements.length,b.elements.length);assert.equal(b.elements.length,432);assert.equal(b.textures.length,1);
function rotate(p,r,inv=false){p=p.slice();for(const axis of inv?[2,1,0]:[0,1,2]){const t=(r[axis]||0)*Math.PI/180*(inv?-1:1),c=Math.cos(t),s=Math.sin(t),[x,y,z]=p;if(axis===0)p=[x,y*c-z*s,y*s+z*c];if(axis===1)p=[x*c+z*s,y,-x*s+z*c];if(axis===2)p=[x*c-y*s,x*s+y*c,z];}return p;}
const add=(p,q)=>p.map((v,i)=>v+q[i]),sub=(p,q)=>p.map((v,i)=>v-q[i]);function point(c,p){const o=c.origin||[0,0,0];return add(rotate(sub(p,o),c.rotation||[0,0,0]),o);}function local(c,p){const o=c.origin||[0,0,0];return add(rotate(sub(p,o),c.rotation||[0,0,0],true),o);}
function corners(c,side){const i=c.inflate||0,lo=c.from.map(v=>v-i),hi=c.to.map(v=>v+i),out=[];for(const a of [0,1])for(const b of [0,1]){let p;if(side==='north'||side==='south')p=[a?hi[0]:lo[0],b?hi[1]:lo[1],side==='north'?lo[2]:hi[2]];else if(side==='east'||side==='west')p=[side==='west'?lo[0]:hi[0],a?hi[1]:lo[1],b?hi[2]:lo[2]];else p=[a?hi[0]:lo[0],side==='down'?lo[1]:hi[1],b?hi[2]:lo[2]];out.push(point(c,p));}return out;}
for(const c of a.elements){const n=bm.get(c.uuid);assert.equal(ap.get(c.uuid),bp.get(c.uuid));for(const k of ['name','from','to','origin','rotation','inflate','visibility','export'])assert.deepEqual(c[k],n[k],c.name+':'+k);for(const [side,f]of Object.entries(c.faces)){const g=n.faces[side],cut=cutMap.get(c.uuid+':'+side);if(f.texture===null){assert.equal(g.texture,null);continue;}if(cut){assert.equal(g.texture,null);continue;}assert.notEqual(g.texture,null);assert.equal(f.rotation,g.rotation);}}
async function main(){const raw=async p=>sharp(Buffer.from(p.textures[0].source.split(',')[1],'base64')).ensureAlpha().raw().toBuffer({resolveWithObject:true}),x=await raw(a),y=await raw(b);assert.equal(y.info.width,512);assert.ok(y.data.equals(await sharp(dir+'/akatsuki-b-optimized.png').ensureAlpha().raw().toBuffer()));function alpha(f){if(f.texture===null)return false;const uv=f.uv;let opaque=true,empty=true;for(let yy=Math.floor(Math.min(uv[1],uv[3]));yy<Math.ceil(Math.max(uv[1],uv[3]));yy++)for(let xx=Math.floor(Math.min(uv[0],uv[2]));xx<Math.ceil(Math.max(uv[0],uv[2]));xx++){const v=x.data[(yy*x.info.width+xx)*4+3];if(v!==255)opaque=false;if(v!==0)empty=false;}return {opaque,empty};}
for(const cut of r.cuts){const c=am.get(cut.uuid);if(cut.reason==='fully-transparent-UV'){assert.ok(alpha(c.faces[cut.side]).empty);continue;}const support=am.get(cut.support);assert.equal(ap.get(c.uuid),ap.get(support.uuid));assert.ok(support.visibility!==false&&support.export!==false);assert.ok(Object.values(support.faces).every(f=>alpha(f).opaque));const points=corners(c,cut.side),i=support.inflate||0,inside=(p,margin)=>p.every((v,k)=>v>support.from[k]-i+margin&&v<support.to[k]+i-margin);if(cut.reason==='strictly-inside-opaque-same-bone')assert.ok(points.every(p=>inside(local(support,p),.0249)));else{assert.ok(points.every(p=>inside(local(support,p),-1e-5)));const center=points.reduce((s,p)=>add(s,p),[0,0,0]).map(v=>v/4),normal=rotate(({north:[0,0,-1],south:[0,0,1],west:[-1,0,0],east:[1,0,0],up:[0,1,0],down:[0,-1,0]})[cut.side],c.rotation||[0,0,0]);assert.ok(inside(local(support,add(center,normal.map(v=>v*.01))),.0009));}}
const sample=(im,uv,u,v)=>{const xx=Math.max(0,Math.min(im.info.width-1,Math.floor(uv[0]+(uv[2]-uv[0])*u))),yy=Math.max(0,Math.min(im.info.height-1,Math.floor(uv[1]+(uv[3]-uv[1])*v))),i=(yy*im.info.width+xx)*4;return im.data.subarray(i,i+4);};let samples=0;for(const c of a.elements)for(const [side,f]of Object.entries(c.faces)){const nf=bm.get(c.uuid).faces[side];if(nf.texture===null)continue;const nx=Math.max(4,Math.ceil(Math.abs(f.uv[2]-f.uv[0]))*2),ny=Math.max(4,Math.ceil(Math.abs(f.uv[3]-f.uv[1]))*2);for(let py=0;py<ny;py++)for(let px=0;px<nx;px++){assert.ok(sample(x,f.uv,(px+.5)/nx,(py+.5)/ny).equals(sample(y,nf.uv,(px+.5)/nx,(py+.5)/ny)),c.name+':'+side);samples++;}}
const geo=read(dir+'/akatsuki-b-optimized.geo.json')['minecraft:geometry'][0],gc=geo.bones.flatMap(g=>g.cubes||[]),faces=gc.reduce((n,c)=>n+Object.keys(c.uv).length,0);assert.equal(gc.length,432);assert.equal(faces,r.stats.afterFaces);assert.equal(geo.description.texture_width,512);const previews=read(dir+'/preview-comparison.json');assert.ok(previews.every(p=>p.changedPixels<=10));r.validation={pass:true,geometryParentsBonesAnimationsAndVisibilityUnchanged:true,removedFaceProofs:r.cuts.length,retainedTexelSamples:samples,retainedTexelsIdentical:true,exportedFaces:faces,texture:[512,512],previews,loader:'TLM 1.5.3 SimpleBedrockModel: omitted per-face UVs set emptyFacesMask and skip vertex submission',runtimeFPSMeasured:false};r.files={sourceModelBytes:fs.statSync(r.source).size,optimizedModelBytes:fs.statSync(dir+'/akatsuki-b-optimized.bbmodel').size,sourceTextureBytes:fs.statSync(dir+'/../midnight-b-full-robe/akatsuki-b-full-robe.png').size,optimizedTextureBytes:fs.statSync(dir+'/akatsuki-b-optimized.png').size,sourceGeometryBytes:fs.statSync(dir+'/../midnight-b-full-robe/akatsuki-b-full-robe.geo.json').size,optimizedGeometryBytes:fs.statSync(dir+'/akatsuki-b-optimized.geo.json').size};fs.writeFileSync(dir+'/culling-report.json',JSON.stringify(r,null,2));console.log(JSON.stringify({stats:r.stats,validation:r.validation,files:r.files}));}
main().catch(e=>{console.error(e);process.exitCode=1;});
